FROM node:8

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# nodemon global
RUN npm install -g nodemon

COPY package.json /usr/src/app/

RUN cd /usr/src/app
RUN npm install && npm cache clean --force

COPY . /usr/src/app

EXPOSE 3000

CMD [ "npm", "start" ]